# Cargo config file. 
# See: https://doc.rust-lang.org/cargo/reference/config.html

# Environments variables set for all `cargo ...` commands.
[env]

# Scope down tracing, to filter out external lib tracing.
RUST_LOG="owl_actix=debug,generate_db=debug"

# -- Service Environment Variables
# IMPORTANT: 
#   For cargo commands only.
#   For deployed env, should be managed by container 
#   (e.g., Kubernetes).

## -- Secrets
# Keys and passwords below are for localhost dev ONLY.
# e.g., "welcome" type of passwords.
# i.e., Encryption not needed.

SERVICE_DB_URL="mariadb://root:31N$t31n@localhost:3306/owl_db"

# SERVICE_PWD_KEY="CKUGFOD9_2Qf6Pn3ZFRYgPYb8ht4vKqEG9PGMXTB7497bT0367DjoaD6ydFnEVaIRda0kKeBZVCT5Hb62m2sCA" # For testing units
SERVICE_PWD_KEY="qr0n_aiBIUmiCzkarDLeORnp257gQdU_T-cRjKEggRS3-7F2HA78fg1nQ3ePSagQOqSyZicCqypv9QZF2rPOKQ"

# SERVICE_TOKEN_KEY="9FoHBmkyxbgu_xFoQK7e0jz3RMNVJWgfvbVn712FBNH9LLaAWS3CS6Zpcg6RveiObvCUb6a2z-uAiLjhLh2igw" # For testing units
SERVICE_TOKEN_KEY="Nuy4s6DgsgizkEcNHE9WR9OP7nEythAIr-kwa_BMV0BwKoeLrXBU45vmAElUbRXStZ-Gugn_ESf82AqK00tRtg"

SERVICE_TOKEN_DURATION_SEC="1800"

## -- Hash Secrets
HASH_SECRET="OWL-project-2024"

## -- JWT Secret
JWT_SECRET="OWL-project-2024"

## -- Backend service
SERVER_HOST="127.0.0.1"
SERVER_PORT="8080"

## -- Config map

# This will be relative to Cargo.toml
# In deployed images, probably use absolute path.
# SERVICE_WEB_FOLDER="web-folder/"
